arch: x86_64
image: archlinux
packages:
  - bash
  - openssh
secrets:
  - ddd49bad-a199-4d6a-910e-5704b4eb747d
  - 8faece3b-a325-416c-9fa1-723fcaf5fa56
sources:
  - https://git.sr.ht/~jae/sitecontent
tasks:
  - publish: bash ~/.bin/publishContent.sh
